---
title: "Learning - Bayes Statistical Rethinking by Richard McElreath"
output: html_notebook
---

****
### My Preface
My problem was to prepare a healthcare summary with comparitive stats along with driver or the cause for a condition or poor or superb performance of a healthcare institution! 

As this Author rightly put, I was not confident on the p-calues or coeffients or accuracies, to consider a diagnosis or a procedure as a driver. I needed to tell a story for a medical director or physician to consider these drivers as a takeaway to investigate or ponder further! 

At this juncture of dilemma, I got introduced to Bayes Network! 

I ran from end to end, reviewing many pdfs, youtube snippets and even the famous coursera course on Bayesian Network aka Probabilitic Graphical models, with less return on the effort put! They initial chapters were easy, later they were getting too complex.

Then I landed on the The book Think Bayes by Allen Downey was savior, along with his youtube tutorial [Bayesian Decision Analysis](https://www.youtube.com/watch?v=fsdbneHgi58) on the same! 

Now trying to expand with Richard McElreath, whose book has been called out by many authors & readers! Lets see how far can I go... fingers crossed!!!!

****
##### DELETE LATER
Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

****

### All models are wrong, but some are useful.

```{r}
# Load the data:
# car braking distances in feet paired with speeds in km/h
# see ?cars for details
data(cars)
# fit a linear regression of distance on speed
m <- lm( dist ~ speed , data=cars )
# estimated coefficients from the model
coef(m)
# plot residuals against speed
plot( resid(m) ~ speed , data=cars )
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
